### ISSUE TITLE
allow starting with a pre-configured listener

### ISSUE THREAD

**Issue by nothingmuch** [payjoin/ohttp-relay#39]
the current code does not allow specifying a listen address and requires a port

making ohttp_relay pub or exposing some other way of starting the relay with a given listener would allow starting the relay in integration tests with an unspecified port thereby avoiding any port allocation race conditions

**Comment by DanGould** [comment]
@nothingmuch may you confirm that this is closed by #41 since that lets us avoid race conditions in tests by returning a port? Or do we specifically need to expose the [`ohttp_relay`](https://github.com/payjoin/ohttp-relay/blob/8e8c147c51b9caa8faba5225f30a3391a2baefc3/src/lib.rs#L72-L75) as a pub function that accepts a listener
